//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v12.0.1+20a4e47
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Outlet</summary>
	[PublishedModel("outlet")]
	public partial class Outlet : PublishedContentModel, ICommon, ICommonFields
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		public new const string ModelTypeAlias = "outlet";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Outlet, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Outlet(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Bread
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bread")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Bread => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "bread");

		///<summary>
		/// Breakfast
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("breakfast")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Breakfast => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "breakfast");

		///<summary>
		/// Cereal
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cereal")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Cereal => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "cereal");

		///<summary>
		/// Dinner
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("dinner")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Dinner => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "dinner");

		///<summary>
		/// Drinks
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("drinks")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Drinks => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "drinks");

		///<summary>
		/// Is Retail
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[ImplementPropertyType("isRetail")]
		public virtual bool IsRetail => this.Value<bool>(_publishedValueFallback, "isRetail");

		///<summary>
		/// Lunch
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("lunch")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Lunch => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "lunch");

		///<summary>
		/// Lunches
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("lunches")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Lunches => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "lunches");

		///<summary>
		/// Ready Meals
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("readyMeals")]
		public virtual global::System.Collections.Generic.IEnumerable<string> ReadyMeals => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "readyMeals");

		///<summary>
		/// Sauces, Dip etc
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("saucesDipEtc")]
		public virtual global::System.Collections.Generic.IEnumerable<string> SaucesDipEtc => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "saucesDipEtc");

		///<summary>
		/// Snack
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("snack")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Snack => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "snack");

		///<summary>
		/// Snacks
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("snacks")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Snacks => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "snacks");

		///<summary>
		/// Soup
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("soup")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Soup => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "soup");

		///<summary>
		/// Treats
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("treats")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Treats => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "treats");

		///<summary>
		/// Hide from Navigation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[ImplementPropertyType("umbracoNaviHide")]
		public virtual bool UmbracoNaviHide => global::Umbraco.Cms.Web.Common.PublishedModels.Common.GetUmbracoNaviHide(this, _publishedValueFallback);

		///<summary>
		/// Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heading")]
		public virtual string Heading => global::Umbraco.Cms.Web.Common.PublishedModels.CommonFields.GetHeading(this, _publishedValueFallback);

		///<summary>
		/// Main Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.0.1+20a4e47")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString MainText => global::Umbraco.Cms.Web.Common.PublishedModels.CommonFields.GetMainText(this, _publishedValueFallback);
	}
}
